var screenDims;var game;setTimeout(function(){window.scrollTo(0,1);var SpilData={id:"576742227280295056"};GameAPI.loadAPI(function(apiInstance){if(window.console&&window.console.log){console.log("GameAPI version "+apiInstance.version+" loaded!");loadedAPI(apiInstance)}},SpilData)},100);
var MainGame={weakDevice:false,orientated:false,onDesktop:false,fadeColor:0,textFPS:null,showFPS:false,isPaused:false,isGoAway:false,isMusicMuted:false,isMusicPlaying:-1,nextState:null,isNextLevel:false,lostLevel:false,s_musicM:null,s_musicG:null,s_sounds1:null,s_sounds2:null,s_sounds3:null,pauseForAds:false,Config:{GAME_WIDTH:356,GAME_HEIGHT:536},linkLogoAPI:null,linkMoreAPI:null,linkTweetAPI:null,logoIsLoaded:false,linkAPI:null,firstTime:true,clickOne:false,showTutorial:false,highscore:0,firstGo:true};
SimpleButton=function(game,kuda,x,y,key,frame,callback,animationScale){this.game=game;if(kuda==null)this.button=this.game.add.sprite(x,y,key,frame);else this.button=kuda.add(this.game.add.sprite(x,y,key,frame));this.button.game=this.game;this.button.anchor.setTo(.5,.5);this.button.inputEnabled=true;if(this.game.device.desktop)this.button.input.useHandCursor=true;this.button.events.onInputDown.add(function(){this.game.add.tween(this.button.scale).to({x:.9,y:.9},200,Phaser.Easing.Cubic.Out,true);this.game.add.tween(this.button.scale).to({x:1,
y:1},200,Phaser.Easing.Cubic.Out,true,260);this.game.time.events.add(250,callback,this)},this);if(typeof animationScale!="undefined")this.game.add.tween(this.button.scale).to({x:animationScale,y:animationScale},630,Phaser.Easing.Linear.None).to({x:1,y:1},630,Phaser.Easing.Linear.None).loop().start()};
function loadedAPI(apiInstance){if(MainGame.logoIsLoaded)return;screenDims=Utils.ScreenUtils.calculateScreenMetrics(356,536,0);game=new Phaser.Game(screenDims.gameWidth,screenDims.gameHeight,Phaser.CANVAS);MainGame.linkLogoAPI=apiInstance.Branding.getLogo();MainGame.linkAPI=apiInstance;if(MainGame.linkLogoAPI.image!=null&&MainGame.linkLogoAPI.image!=false){MainGame.logoIsLoaded=true;apiInstance.Branding.listLinks();MainGame.linkMoreAPI=apiInstance.Branding.getLink("more_games");MainGame.linkTweetAPI=
apiInstance.Branding.getLink("twitter")}game.state.add("Boot",MainGame.Boot,true);game.state.add("Preloader",MainGame.Preloader);game.state.add("Menu",MainGame.MainMenu);game.state.add("Game",MainGame.Game);game.state.add("Credits",MainGame.Credits);setTimeout(function(){window.scrollTo(0,1)},100)}function continueGame(){game.state.start("Menu")}
function addLogo(vX,vY,vScale,vIsCenter){if(typeof vIsCenter==="undefined")vIsCenter=false;if(MainGame.logoIsLoaded===true){var logo=game.add.sprite(vX,vY,"logoSponsor");if(vIsCenter)logo.anchor.setTo(.5,.5);logo.scale.setTo(vScale,vScale);logo.inputEnabled=true;logo.events.onInputDown.add(clickLogo2,this)}}function showFps(){game.time.advancedTiming=true;MainGame.textFPS=game.add.text(260,10,"FPS",{font:"22px Arial",fill:"#FFFFFF",align:"center"});MainGame.textFPS.fixedToCamera=true}
function trace(a){console.log(a)}function clickShare(){var text="Yay I got "+MainGame.highscore+" on Captain Rockets! Can you beat me? ";var tweetbegin="http://twitter.com/home?status=";var tweettxt=text+" http://www.a10.com/action-games/general-rockets #CaptainRockets";var finaltweet=tweetbegin+encodeURIComponent(tweettxt);window.open(finaltweet,"_blank")}
function clickLogo(){if(MainGame.clickOne)return;if(MainGame.logoIsLoaded===true)if(!MainGame.linkMoreAPI.error)MainGame.linkMoreAPI.action();MainGame.clickOne=true;game.time.events.add(500,clickOneBack,this)}function clickLogo2(){if(MainGame.clickOne)return;if(MainGame.logoIsLoaded===true)if(!MainGame.linkMoreAPI.error)MainGame.linkLogoAPI.action();MainGame.clickOne=true;game.time.events.add(500,clickOneBack,this)}function clickOneBack(){MainGame.clickOne=false}
function clickSplash(){if(MainGame.logoIsLoaded===true){var splashScreenData=MainGame.linkAPI.Branding.getSplashScreen();if(splashScreenData.action!=null)splashScreenData.action()}}function clearGame(){game.tweens.removeAll()}
function goToState(pNextState){game.tweens.removeAll();var spr_bg=this.game.add.graphics(0,0);spr_bg.beginFill(MainGame.fadeColor,1);spr_bg.drawRect(0,0,this.game.width,this.game.height);spr_bg.alpha=0;spr_bg.endFill();MainGame.nextState=pNextState;var s=this.game.add.tween(spr_bg);s.to({alpha:1},200,Phaser.Easing.Linear.None);s.onComplete.add(this.changeState,this);s.start()}
function goChangeState(pNextState){game.tweens.removeAll();var spr_bg=this.game.state.states.Game.panelScreen.add(this.game.add.graphics(-MainGame.sdvigX,0));spr_bg.beginFill(MainGame.fadeColor,1);spr_bg.drawRect(0,0,this.game.width,this.game.height);spr_bg.alpha=0;spr_bg.endFill();MainGame.nextState=pNextState;var s=this.game.add.tween(spr_bg);s.to({alpha:1},400,Phaser.Easing.Linear.None);s.onComplete.add(this.changeState,this);s.start()}
function changeState(){this.game.state.start(MainGame.nextState);if(MainGame.isNextLevel)this.game.state.start("game")}function fadeOut(){var spr_bg=this.game.add.graphics(0,0);spr_bg.beginFill(MainGame.fadeColor,1);spr_bg.drawRect(0,0,this.game.width,this.game.height);spr_bg.alpha=1;spr_bg.endFill();game.add.tween(spr_bg).to({alpha:0},150,Phaser.Easing.Linear.None).start()}function clearSaves(){}
function muteSounds(btn){this.game.add.tween(btn.scale).to({x:.9,y:.9},200,Phaser.Easing.Cubic.Out,true);this.game.add.tween(btn.scale).to({x:1,y:1},200,Phaser.Easing.Cubic.Out,true,260);if(game.sound.mute){btn.frameName="btn_sound_on_0000";btn.x=63;btn.y=331}else{btn.frameName="btn_sound_off_0000";btn.x=63;btn.y=330}game.sound.mute=!game.sound.mute;MainGame.isMusicMuted=game.sound.mute}
function playMusic(num){if(MainGame.isMusicPlaying===num)return;MainGame.s_musicM.play("",0,1,true);MainGame.isMusicPlaying=num}function stopMusic(){if(game.device.webAudio){MainGame.isMusicPlaying=-1;if(MainGame.s_musicM!=null)MainGame.s_musicM.stop()}}function playSound(num){if(game.device.webAudio)switch(num){case 1:MainGame.s_sounds1.play();break;case 2:MainGame.s_sounds2.play();break;case 3:MainGame.s_sounds3.play();break}}
function getRandomInt(min,max){return Math.floor(Math.random()*(max-min+1))+min}function shuffleArr(o){for(var j,x,i=o.length;i;j=Math.floor(Math.random()*i),x=o[--i],o[i]=o[j],o[j]=x);return o};
MainGame.MainMenu=function(game){this.playButton=null;this.moreGames=null;this.musicButton=null;this.creditsButton=null;this.box=null;this.bear=null;this.layerMain=null};
MainGame.MainMenu.prototype={create:function(){var bg=game.add.sprite(MainGame.oldWorldX,MainGame.oldWorldY,"main");bg.anchor.setTo(.5,.5);bg.fixedToCamera=true;this.layerMain=game.add.group();this.layerMain.x=MainGame.sdvigX;var title=this.layerMain.add(game.add.sprite(178,170,"bg_menu"));title.anchor.setTo(.5,.5);this.playButton=new SimpleButton(game,this.layerMain,178,330,"ss_main","btn_play_0000",this.startGame,1.1);this.moreGames=this.layerMain.add(game.add.sprite(178,445,"ss_main","btn_moregames_0000"));
this.moreGames.anchor.setTo(.5,.5);this.moreGames.inputEnabled=true;this.moreGames.events.onInputDown.add(clickLogo,this);this.creditsButton=new SimpleButton(game,this.layerMain,293,330,"ss_main","btn_options_0000",this.goCredits);this.musicButton=this.layerMain.add(game.add.sprite(63,330,"ss_main","btn_sound_on_0000"));this.musicButton.anchor.setTo(.5,.5);this.musicButton.inputEnabled=true;this.musicButton.events.onInputDown.add(muteSounds,this);if(MainGame.isMusicMuted)this.musicButton.frameName=
"btn_sound_off_0000";if(MainGame.firstGo)this.musicButton.frameName="btn_sound_off_0000";else playMusic(0);addLogo(-5+MainGame.sdvigX,10,.8,false);game.input.onDown.addOnce(this.playOnce,this);MainGame.showTutorial=true;var skok=localStorage["generalRocketScore"];if(skok!=undefined&&skok!="null")MainGame.highscore=Number(skok);fadeOut()},playOnce:function(){if(!MainGame.firstGo)return;MainGame.firstGo=false;this.musicButton.frameName="btn_sound_on_0000";this.musicButton.x=63;this.musicButton.y=331;
playMusic(0)},update:function(){},goCredits:function(){goToState("Credits")},startGame:function(pointer){goToState("Game")}};
MainGame.Preloader=function(game){this.background=null;this.preloadBar=null;this.ready=false};
MainGame.Preloader.prototype={preload:function(){game.stage.backgroundColor="#0E93CB";addLogo(MainGame.Config.SCREEN_MIDX,MainGame.Config.SCREEN_MIDY+130,1,true);this.background=this.add.sprite(MainGame.Config.SCREEN_MIDX-155,MainGame.Config.SCREEN_MIDY+40,"preloaderBackground");this.preloadBar=this.add.sprite(MainGame.Config.SCREEN_MIDX-155,MainGame.Config.SCREEN_MIDY+40,"preloaderBar");this.load.setPreloadSprite(this.preloadBar);game.load.audio("music-menu",["assets/audio/ogg/music.ogg","assets/audio/m4a/music.m4a"]);
if(this.game.device.webAudio){game.load.audio("sfx_gameover",["assets/audio/ogg/sfx_gameover.ogg","assets/audio/m4a/sfx_gameover.m4a"]);game.load.audio("sfx_hit",["assets/audio/ogg/sfx_hit.ogg","assets/audio/m4a/sfx_hit.m4a"]);game.load.audio("sfx_jump",["assets/audio/ogg/sfx_jump.ogg","assets/audio/m4a/sfx_jump.m4a"])}game.load.atlasJSONHash("ss_main","assets/ss_main.png?r=3","assets/ss_main.json?r=3");game.load.atlasJSONHash("ss_hero","assets/ss_hero.png?r=3","assets/ss_hero.json?r=3");game.load.image("bg_blur",
"assets/backgrounds/blur.png?r=4");game.load.image("bg_menu","assets/backgrounds/menu.png?r=4");game.load.image("bg_credit","assets/backgrounds/credit.png?r=4");game.load.image("bg_gameover","assets/backgrounds/gameover.png?r=4");game.load.image("box","assets/platform.png?r=1");game.load.bitmapFont("dereza2","assets/fonts/bmf_dereza2_0.png","assets/fonts/bmf_dereza2.fnt");game.load.bitmapFont("bmf_melma","assets/fonts/bmf_melma_0.png","assets/fonts/bmf_melma.fnt")},create:function(){MainGame.s_musicM=
game.add.audio("music-menu",1,true);MainGame.s_sounds1=game.add.audio("sfx_gameover",1);MainGame.s_sounds2=game.add.audio("sfx_hit",1);MainGame.s_sounds3=game.add.audio("sfx_jump",1);this.preloadBar.cropEnabled=false},update:function(){if(this.ready==false){this.ready=true;MainGame.linkAPI.Branding.displaySplashScreen(continueGame)}}};
MainGame.Boot=function(game){};
MainGame.Boot.prototype={init:function(){this.input.maxPointers=1;var screenDims=Utils.ScreenUtils.screenMetrics;if(this.game.device.desktop){console.log("DESKTOP");this.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;this.scale.pageAlignHorizontally=true;this.scale.setScreenSize(true)}else{console.log("MOBILE");this.scale.scaleMode=Phaser.ScaleManager.USER_SCALE;this.scale.setUserScale(screenDims.scaleX,screenDims.scaleY);this.scale.pageAlignHorizontally=true;this.scale.pageAlignVertically=true;this.scale.forceOrientation(false,
true);this.scale.enterIncorrectOrientation.add(this.enterIncorrectOrientation,this);this.scale.leaveIncorrectOrientation.add(this.leaveIncorrectOrientation,this)}MainGame.sdvigX=Math.floor(Math.abs(screenDims.defaultGameWidth-screenDims.gameWidth)/2);MainGame.Config.GAME_WIDTH=screenDims.gameWidth;MainGame.Config.GAME_HEIGHT=screenDims.gameHeight;MainGame.Config.SCREEN_MIDX=screenDims.gameWidth/2;MainGame.Config.SCREEN_MIDY=screenDims.gameHeight/2;this.game.onPause.add(this.onGamePause,this);this.game.onResume.add(this.onGameResume,
this);MainGame.oldWorldX=this.world.centerX;MainGame.oldWorldY=this.world.centerY},preload:function(){this.load.image("main","assets/backgrounds/main.png?r=3");this.load.image("preloaderBackground","assets/loading_off.png?r=2");this.load.image("preloaderBar","assets/loading_on.png?r=2");if(MainGame.linkLogoAPI.image!=null&&MainGame.linkLogoAPI.image!=false)game.load.image("logoSponsor",MainGame.linkLogoAPI.image)},create:function(){this.state.start("Preloader")},onGamePause:function(){if(!MainGame.supportAudio)return;
if(!game.sound.mute){MainGame.isGoAway=true;game.sound.mute=true}else MainGame.isGoAway=false},onGameResume:function(){if(!MainGame.supportAudio)return;if(MainGame.isGoAway)game.sound.mute=false},gameResized:function(width,height){},enterIncorrectOrientation:function(){setTimeout(function(){window.scrollTo(0,1)},100);MainGame.orientated=false;document.getElementById("orientation").style.display="block"},leaveIncorrectOrientation:function(){setTimeout(function(){window.scrollTo(0,1)},100);MainGame.orientated=
true;document.getElementById("orientation").style.display="none"}};
Rocket1=function(vX,vY,game,player,camera,platforms){this.game=game;this.player=player;this.camera=camera;this.alive=true;this.tank=platforms.add(game.add.sprite(vX,vY,"ss_hero"));this.tank.anchor.setTo(.5,.5);this.tank.animations.add("rocket1",Phaser.Animation.generateFrameNames("rocket1_",0,3,"",4),30);this.tank.animations.play("rocket1",30,true);this.tank.body.immovable=true;this.tank.body.setSize(32,25,-10,0)};
Rocket1.prototype.update=function(){this.tank.x-=3;if(this.tank.x<this.camera.x-200){this.tank.kill();var index=game.state.states.Game.enemies.indexOf(this);if(index>-1){game.state.states.Game.enemies.splice(index,1);game.state.states.Game.enemiesTotal=game.state.states.Game.enemies.length}}};
Rocket2=function(vX,vY,game,player,camera,platforms){this.game=game;this.player=player;this.camera=camera;this.alive=true;this.timerDum=0;this.tank=platforms.add(game.add.sprite(vX,vY,"ss_hero"));this.tank.anchor.setTo(.5,.5);this.tank.animations.add("rocket2",Phaser.Animation.generateFrameNames("rocket2_",0,3,"",4),30);this.tank.animations.play("rocket2",30,true);this.tank.body.immovable=true;this.tank.body.setSize(32,25,-10,0)};
Rocket2.prototype.update=function(){this.tank.x-=4;if(this.tank.x<this.camera.x-200){this.tank.x=this.camera.x+1500;this.tank.y=getRandomInt(8,18)*25}else{this.timerDum++;if(this.timerDum>6){game.state.states.Game.addDum(this.tank.x,this.tank.y);this.timerDum=0}}};
Rocket3=function(vX,vY,game,player,camera,platforms){this.game=game;this.player=player;this.camera=camera;this.alive=true;this.tank=platforms.add(game.add.sprite(vX,vY,"ss_hero"));this.tank.anchor.setTo(.5,.5);this.tank.animations.add("rocket3",Phaser.Animation.generateFrameNames("rocket3_",0,3,"",4),30);this.tank.animations.play("rocket3",30,true);this.tank.body.immovable=true;this.tank.body.setSize(32,25,-10,0);game.add.tween(this.tank).to({y:vY+40},700,Phaser.Easing.Linear.None,true,0,-1,true)};
Rocket3.prototype.update=function(){this.tank.x-=4;if(this.tank.x<this.camera.x-200){this.tank.x=this.camera.x+1500;this.tank.y=getRandomInt(8,18)*25}};
MainGame.Credits=function(game){this.layerMain=null;this.backButton=null};
MainGame.Credits.prototype={create:function(){var bg=game.add.sprite(MainGame.oldWorldX,MainGame.oldWorldY,"main");bg.anchor.setTo(.5,.5);bg.fixedToCamera=true;this.layerMain=game.add.group();this.layerMain.x=MainGame.sdvigX;var title=this.layerMain.add(game.add.sprite(178,220,"bg_credit"));title.anchor.setTo(.5,.5);addLogo(-5+MainGame.sdvigX,10,.8,false);this.creditsButton=new SimpleButton(game,this.layerMain,178,394,"ss_main","btn_home_0000",this.goToMenu);fadeOut()},goToMenu:function(){goToState("Menu")},
update:function(){}};
MainGame.Game=function(game){this.layerMain=null;this.player=null;this.camera=null;this.bridge=null;this.midX=178;this.direction=1;this.oneAction=true;this.firstJump=false;this.platforms=null;this.enemiesTotal=0;this.enemies=null;this.poolDum=null;this.arrow1=null;this.arrow2=null;this.tuttext=null;this.ppcpalka=null;this.plashka=null;this.scoreGame=0;this.scoreText=null;this.dist_c=0;this.dist_m=0};
MainGame.Game.prototype={create:function(){MainGame.gameOver=false;var bg=game.add.sprite(MainGame.oldWorldX,MainGame.oldWorldY,"main");bg.anchor.setTo(.5,.5);bg.fixedToCamera=true;this.layerMain=game.add.group();this.layerMain.x=MainGame.sdvigX;this.createLevel();this.createButtons();fadeOut()},createLevel:function(){MainGame.debug=false;game.physics.startSystem(Phaser.Physics.ARCADE);game.physics.arcade.OVERLAP_BIAS=20;game.physics.arcade.maxObjects=2;game.physics.arcade.forceX=true;this.layerGame=
this.layerMain.add(game.add.group());this.plashka=this.layerGame.add(game.add.sprite(130,50,"ss_main","plashka_0000"));this.plashka.fixedToCamera=true;this.scoreText=this.layerGame.add(game.add.bitmapText(170,56,"bmf_melma","0",34));this.scoreText.fixedToCamera=true;this.scoreText.tint=14869218;this.bridge=this.layerGame.add(game.add.sprite(0,277,"ss_hero","bridge_0000"));this.ppcpalka=this.layerGame.add(game.add.sprite(-200,90,"ss_hero","wall_0000"));game.physics.enable(this.ppcpalka);this.ppcpalka.body.immovable=
true;this.ppcpalka.body.velocity.x=65;this.addPlayer(40,262);this.platforms=this.layerMain.add(game.add.group());this.platforms.enableBody=true;game.world.setBounds(0,0,2E3,356);game.input.onDown.add(this.jumpMan,this);this.direction=1;this.oneAction=true;this.firstJump=false;this.enemiesTotal=0;this.enemies=[];this.enemies.push(new Rocket1(600,300,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket1(650,300,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket1(700,
300,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket1(750,300,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket1(850,getRandomInt(8,18)*25,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket2(2E3,getRandomInt(8,18)*25,game,this.player,this.camera,this.platforms));this.enemies.push(new Rocket3(4E3,getRandomInt(8,18)*25,game,this.player,this.camera,this.platforms));this.enemiesTotal=this.enemies.length;this.poolDum=this.layerGame.add(game.add.group());
this.poolDum.createMultiple(20,"ss_hero","dim_0000");this.poolDum.forEach(this.setupExplosion,this);this.scoreGame=0;this.dist_c=0;this.dist_m=0;playMusic(0)},addDum:function(vX,vY){var obj=game.state.states.Game.poolDum.getFirstExists(false);if(obj!=null){obj.reset(vX+30,vY);game.time.events.add(800,this.removeDum,this,obj)}},removeDum:function(obj){obj.kill()},setupExplosion:function(obj){obj.anchor.x=.5;obj.anchor.y=.5},initTimer:function(){game.time.events.loop(400,this.updateTimer1,this)},updateTimer1:function(){var vX=
this.camera.x+700;var vY=getRandomInt(8,18)*25;this.enemies.push(new Rocket1(vX,vY,game,this.player,this.camera,this.platforms));this.enemiesTotal=this.enemies.length},addPlayer:function(vX,vY){this.player=this.layerGame.add(game.add.sprite(vX,vY,"ss_hero"));this.player.anchor.setTo(.5,.5);this.player.animations.add("hero_run",Phaser.Animation.generateFrameNames("hero_run_",0,21,"",4),30);this.player.animations.add("hero_jump2",Phaser.Animation.generateFrameNames("hero_jump2_",0,1,"",4),30);this.player.animations.add("hero_dead",
Phaser.Animation.generateFrameNames("hero_dead_",0,1,"",4),30);this.player.animations.play("hero_jump2",30,true);game.physics.enable(this.player);this.player.body.collideWorldBounds=false;this.player.body.setSize(24,25,0,0);this.camera=this.layerGame.add(game.add.sprite(vX,vY));game.camera.follow(this.camera);game.time.events.add(500,this.initRuning,this)},initRuning:function(){this.player.animations.play("hero_run",30,true);this.player.body.velocity.x=170;this.initTimer();game.add.tween(game.state.states.Game.bridge).to({x:-100},
2E3,Phaser.Easing.Linear.None,true,500).onComplete.add(function(){game.state.states.Game.bridge.kill()})},initJumping:function(){this.player.body.gravity.y=1100;this.player.body.velocity.y=-550;this.player.body.velocity.x=200;this.player.animations.play("hero_jump2",30,true);playSound(3)},jumpMan:function(){if(!this.firstJump)return;if(MainGame.gameOver)return;if(this.game.input.x>this.midX)this.direction=-1;else this.direction=1;this.player.scale.setTo(-this.direction,1)},addBox:function(vX,vY,vW,
vH){var box=this.platforms.add(game.add.sprite(vX,vY,"ss_hero"));box.anchor.setTo(.5,.5);box.animations.add("rocket1",Phaser.Animation.generateFrameNames("rocket1_",0,3,"",4),30);box.animations.play("rocket1",30,true);box.body.immovable=true;box.body.setSize(30,20,-10,0)},createButtons:function(){this.fixedScreen=this.layerMain.add(game.add.group());this.panelScreen=this.layerMain.add(game.add.group());this.fixedScreen.fixedToCamera=true;this.panelScreen.fixedToCamera=true;this.fixedScreen.alpha=
0;if(MainGame.showFPS)showFps();this.addGameLogo(-5,7,.8,false);this.arrow1=this.panelScreen.add(game.add.sprite(15+77,410,"ss_main","btn_arrow_0000"));this.arrow1.scale.setTo(-1,1);this.arrow2=this.panelScreen.add(game.add.sprite(356-15-77,410,"ss_main","btn_arrow_0000"));if(MainGame.showTutorial){this.tuttext=this.panelScreen.add(game.add.sprite(178,150,"ss_main","tutorial_0000"));this.tuttext.anchor.setTo(.5,.5)}game.input.onDown.addOnce(this.removeTutorial,this)},removeTutorial:function(){if(this.arrow2!=
null)if(this.arrow2.alpha<1)return;game.add.tween(this.arrow1).to({alpha:0},400,Phaser.Easing.Linear.None,true).onComplete.add(function(){game.state.states.Game.arrow1.kill()});game.add.tween(this.arrow2).to({alpha:0},400,Phaser.Easing.Linear.None,true).onComplete.add(function(){game.state.states.Game.arrow2.kill()});if(MainGame.showTutorial)game.add.tween(this.tuttext).to({alpha:0},400,Phaser.Easing.Linear.None,true).onComplete.add(function(){game.state.states.Game.tuttext.kill();MainGame.showTutorial=
false})},createButtonsFinish:function(){game.add.tween(this.fixedScreen).to({alpha:1},100,Phaser.Easing.Linear.None,true);var bg=this.fixedScreen.add(game.add.sprite(MainGame.oldWorldX,MainGame.oldWorldY,"bg_blur"));bg.anchor.setTo(.5,.5);this.fixedScreen.add(game.add.sprite(26,84,"bg_gameover"));var medalka;if(this.scoreGame>=5){medalka=this.fixedScreen.add(game.add.sprite(73,193,"ss_main","medal_0000"));if(this.scoreGame>=10){medalka.frameName="medal_0001";if(this.scoreGame>=15)medalka.frameName=
"medal_0002"}}if(this.scoreGame>MainGame.highscore){MainGame.highscore=this.scoreGame;localStorage["generalRocketScore"]=this.scoreGame}if(this.scoreGame>0)GameAPI.Score.submit(this.scoreGame);var textC1=this.fixedScreen.add(game.add.bitmapText(262,185,"bmf_melma",String(this.scoreGame),34));textC1.tint=14869218;var textC2=this.fixedScreen.add(game.add.bitmapText(262,185+70,"bmf_melma",String(MainGame.highscore),34));textC2.tint=14869218;var replayButton=new SimpleButton(game,this.fixedScreen,178,
377,"ss_main","btn_replay_0000",this.replayGame);var homeButton=new SimpleButton(game,this.fixedScreen,65,377+5,"ss_main","btn_home_0000",this.goToMenu);var share=this.fixedScreen.add(game.add.sprite(291,377+5,"ss_main","btn_share_0000"));share.anchor.setTo(.5,.5);share.inputEnabled=true;share.events.onInputDown.add(clickShare,this);var moreGames=this.fixedScreen.add(game.add.sprite(178,485,"ss_main","btn_moregames_0000"));moreGames.anchor.setTo(.5,.5);moreGames.inputEnabled=true;moreGames.events.onInputDown.add(clickLogo,
this)},clickShare:function(){var text="Yay I got "+MainGame.highscore+" on Captain Rockets! Can you beat me?";var tweetbegin="http://twitter.com/home?status=";var tweettxt=text+window.location.href;var finaltweet=tweetbegin+encodeURIComponent(tweettxt);window.open(finaltweet,"_blank")},goToMenu:function(){goChangeState("Menu")},replayGame:function(){goChangeState("Game")},addGameLogo:function(vX,vY,vScale,vIsCenter){if(typeof vIsCenter==="undefined")vIsCenter=false;if(MainGame.logoIsLoaded===true){var logo=
this.panelScreen.add(game.add.sprite(vX,vY,"logoSponsor"));if(vIsCenter)logo.anchor.setTo(.5,.5);logo.scale.setTo(vScale,vScale);logo.inputEnabled=true;logo.events.onInputDown.add(MainGame.linkLogoAPI.action,this)}},update:function(){if(MainGame.showFPS)MainGame.textFPS.setText("FPS: "+game.time.fps);if(MainGame.isPaused)return;if(MainGame.gameOver){if(game.input.keyboard.isDown(Phaser.Keyboard.SPACEBAR))this.replayGame();return}if(this.camera.x<this.player.x)this.camera.x=this.player.x;if(this.oneAction){if(this.player.x>
130){this.oneAction=false;this.initJumping()}}else{if(this.firstJump){if(this.input.activePointer.isDown)if(this.direction<0)this.player.x+=3;else this.player.x-=3;if(game.input.keyboard.isDown(Phaser.Keyboard.LEFT)){this.player.x-=3;this.removeTutorial()}else if(game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)){this.player.x+=3;this.removeTutorial()}}if(this.player.x>300){this.dist_c=Math.floor((this.player.x-300)/100);if(this.dist_c>this.dist_m){this.dist_m=this.dist_c;this.scoreGame=this.dist_m;
this.scoreText.setText(String(this.scoreGame))}}if(this.player.y>700){this.loseGame();return}}game.physics.arcade.collide(this.player,this.platforms,this.collideRocket);game.physics.arcade.collide(this.player,this.ppcpalka,this.collideWall);for(var i=0;i<this.enemiesTotal;i++)if(this.enemies[i].alive)this.enemies[i].update()},collideRocket:function(player,object){if(player.body.touching.down || game.state.states.Game.firstJump){player.body.velocity.y=-550;player.body.velocity.x=0;playSound(3);game.state.states.Game.firstJump=true}else{MainGame.gameOver=
true;player.body.gravity.y=0;player.body.velocity.y=0;player.body.velocity.x=0;game.state.states.Game.ppcpalka.body.velocity.x=0;player.animations.play("hero_dead",30,true);game.state.states.Game.addBoom(object.x,object.y);game.add.tween(player).to({y:600},900,Phaser.Easing.Linear.None,true,600);game.add.tween(player).to({angle:90},900,Phaser.Easing.Linear.None,true,600);object.kill();game.time.events.add(1800,game.state.states.Game.loseGame,game)}},collideWall:function(player,object){MainGame.gameOver=
true;player.body.gravity.y=0;player.body.velocity.y=0;player.body.velocity.x=0;game.state.states.Game.ppcpalka.body.velocity.x=0;player.animations.play("hero_dead",30,true);game.add.tween(player).to({y:600},900,Phaser.Easing.Linear.None,true,300);game.add.tween(player).to({angle:90},900,Phaser.Easing.Linear.None,true,300);game.time.events.add(1800,game.state.states.Game.loseGame,game)},addBoom:function(vX,vY){var obj=this.layerGame.add(game.add.sprite(vX,vY,"ss_hero"));obj.anchor.setTo(.5,.5);obj.animations.add("boom_guard2",
Phaser.Animation.generateFrameNames("boom_guard2_",0,14,"",4),30);obj.animations.play("boom_guard2",30,false,true);playSound(2)},loseGame:function(){if(game.state.states.Game.arrow1!=null)game.state.states.Game.removeTutorial();playSound(1);game.state.states.Game.ppcpalka.body.velocity.x=0;game.state.states.Game.player.kill();game.state.states.Game.plashka.kill();game.state.states.Game.scoreText.kill();MainGame.gameOver=true;game.state.states.Game.enemiesTotal=game.state.states.Game.enemies.length;
for(var i=0;i<game.state.states.Game.enemiesTotal;i++)if(game.state.states.Game.enemies[i].alive)game.state.states.Game.enemies[i].tank.kill();game.state.states.Game.enemies=[];game.state.states.Game.poolDum.removeAll();game.state.states.Game.ppcpalka.kill();game.state.states.Game.createButtonsFinish();GameAPI.GameBreak.request(game.state.states.Game.fnPause,game.state.states.Game.fnResume)},fnPause:function(){if(!game.sound.mute){MainGame.isGoAway=true;game.sound.mute=true}else MainGame.isGoAway=
false},fnResume:function(){if(MainGame.isGoAway)game.sound.mute=false}};
